spring:
    output:
        ansi:
            enabled: always
    datasource:
        url: jdbc:mysql://localhost:3306/escahe_bank
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true